config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users, controllers: { registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions', confirmations: 'users/confirmations',
    passwords: 'users/passwords'
    }
  devise_scope :user do
    get '/users/sign_out', to: 'users/sessions#destroy'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'map/index'
  get 'areas/show'

  root 'static_pages#home'
  get'/about', to: 'static_pages#about'
  get'/contact', to: 'static_pages#contact'
  get'/advertise', to: 'static_pages#advertise'
  get'/terms', to: 'static_pages#terms'
  get'/policy', to: 'static_pages#policy'
  get '/', to: 'areas#show'

  resources :areas, param: :slag do
    resources :spaces, only: [:show] do
      member do
        get 'review'
        get 'photo'
        get 'map'
      end
    end
  end

  resources :spaces, only: [:show] do
    collection do
      get 'search'
    end
  end

  resources :reviews
  resources :users, only: [:show]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @users = User.all
    @spaces = Space.all
    @reviews = Review.all
    @areas = Area.all
  end

  def about
  end

  def contact
  end

  def advertise
  end

  def terms
  end

  def policy
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "スペースハッカーについて") %>
<section class="about container">
  <div class="title">
    <h2>スペースハッカーについて</h2>
  </div>
</section>

app/views/static_pages/advertise.html.erb
<% provide(:title, "広告掲載") %>
<section class="contact">
  <div class="title page-form account-form">
    <h2>店舗さま向けお問い合わせフォーム</h2>
    <form>
      <p>スペースハッカーにあなたの施設を掲載してみませんか？掲載は無料から可能となているので、お気軽にご連絡ください。</p>
      <div class="form-group">
        <input type="name" class="form-control" id="exampleInputName" placeholder="コワーキングスペース/カフェ名">
      </div>
      <div class="form-group">
        <input type="email" class="form-control" id="exampleInputEmail" placeholder="ご担当者名">
      </div>
      <div class="form-group">
        <input type="password" class="form-control" id="exampleInputPassword" placeholder="メールアドレス">
      </div>
      <div class="form-group">
        <input type="confirmation" class="form-control" id="exampleInputConfirmation" placeholder="電話番号">
      </div>
      <div class="form-group">
        <input type="confirmation" class="form-control" id="exampleInputConfirmation" placeholder="お問い合わせ内容">
      </div>
      <div class="form-group">
        <textarea type="contents" class="form-control" rows="5" placeholder="ご不明点・ご質問など"></textarea>
      </div>
      <button class="btn btn-form" type="submit">お問い合わせを送信する</button>
    </form>
  </div>
</section>

app/views/static_pages/contact.html.erb
<% provide(:title, "お問い合わせ") %>
<section class="contact">
  <div class="title page-form account-form">
    <h2>お問い合わせフォーム</h2>
    <form>
      <p>SpaceHackerを日頃よりご利用いただき誠にありがとうございます。ご質問・ご意見があれば、お気軽にお問い合わせくださいませ。</p>
      <div class="form-group">
        <input type="name" class="form-control" id="exampleInputName" placeholder="お名前">
      </div>
      <div class="form-group">
        <input type="mail" class="form-control" id="exampleInputMail" placeholder="メールアドレス">
      </div>
      <div class="form-group">
        <textarea type="contents" class="form-control" rows="5" placeholder="ご不明点・ご質問など"></textarea>
      </div>
      <button class="btn btn-form" type="submit">お問い合わせを送信する</button>
    </form>
  </div>
</section>

app/views/static_pages/home.html.erb
<!-- Section 1 : Featured Cover -->
<section class="featured-cover">
  <div class="jumbotron featured" style="background:url(/images/featured_img.jpg) center no-repeat; background-size: cover;">
    <div class="container hero">
      <h1>あなたのとっておきスペースを見つけよう</h1>
      <p>外出先で使えるコワーキングスペース / カフェの口コミを掲載中！</p>
      <p>仕事で使えるスペース探し</p>
    </div>
    <!-- min-width: 767px for desktop -->
    <div class="desktop desktop-featured">
      <%= search_form_for @search, url: search_spaces_path do |f| %>
      <form class="navbar-form" role="search">
        <ul class="form-group desktop-featured-search">
          <li>
            <%= f.text_field :description_cont, placeholder: "キーワードを検索する", class: "form-control" %>
          </li>
          <li class="dropdown featured-menu">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              エリアから検索
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><%= link_to "渋谷・恵比寿・代官山", area_path("shibuya") %></li>
              <li><%= link_to "新宿・代々木", area_path("shinjuku") %></li>
              <li><%= link_to "原宿・青山・表参道", area_path("harajuku") %></li>
              <li><%= link_to "秋葉原・神田", area_path("akihabara") %></li>
              <li><%= link_to "東京・日本橋", area_path("tokyo") %></li>
              <li><%= link_to "六本木・麻布・広尾", area_path("roppongi") %></li>
            </ul>
          </li>
          <li>
            <%= f.submit ("検索する"), class: "btn btn-form featured-btn" %>
          </li>
          <% end %>
        </ul>
      </form>
    </div>
    <!-- /min-width: 767px for desktop -->

    <!-- max-width: 767px for mobile -->
    <div class="mobile mobile-featured">
        <div class="keyword-menu">
          <input type="text" class="form-control" placeholder="キーワードから検索する">
        </div>
        <div class="dropdown featured-menu">
          <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            エリアから検索
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
            <li><%= link_to "渋谷・恵比寿・代官山", area_path("shibuya") %></li>
            <li><%= link_to "新宿・代々木", area_path("shinjuku") %></li>
            <li><%= link_to "原宿・青山・表参道", area_path("harajuku") %></li>
            <li><%= link_to "秋葉原・神田", area_path("akihabara") %></li>
            <li><%= link_to "東京・日本橋", area_path("tokyo") %></li>
            <li><%= link_to "六本木・麻布・広尾", area_path("roppongi") %></li>
          </ul>
        </div>
    </div>
    <!-- /max-width: 767px for mobile -->
  </div>
</section>
<!-- /Section 1 : Featured Cover -->

<!-- Section 2 : Popular Space -->
<section class="container popular-space">
  <div class="title">
    <h2>話題のスペース</h2>
    <!-- min-width: 767px for desktop -->
    <% @spaces.first(3).each do |space| %>
    <div class="desktop desktop-popular-space">
      <%= link_to area_space_path(area_slag: space.area.slag, id: space.id) do %>
        <div class="col-md-4 col-sm-4 card">
          <%= image_tag space.image, class: "card-img" %>
          <div class="card-contents">
            <h3 class="card-contents-title"><%= space.name %></h3>
            <span class="rate rate45 card-rate"></span>
            <p class="card-contents-genre"><%= space.genre %></p>
            <p class="card-contents-sign"><img src="/images/map-marker.png" /><span><%= space.area.try(:name) %></span></p>
          </div>
        </div>
      <% end %>
    </div>

    <div class="mobile mobile-popular-space">
      <%= link_to area_space_path(area_slag: space.area.slag, id: space.id) do %>
        <div class="col-xs-4 mobile-card">
          <%= image_tag space.image, class: "mobile-card-img" %>
          <div class="mobile-card-contents">
            <h3 class="mobile-card-contents-title"><%= space.name %></h3>
            <span class="rate rate15 mobile-card-rate"></span>
            <p class="mobile-card-contents-genre"><%= space.genre %></p>
            <p class="mobile-card-contents-sign"><img src="/images/map-marker.png" /><span>原宿・表参道・青山</span></p>
          </div>
        </div>
      <% end %>
    </div>
    <% end %>
    <div class="space-all container">
      <%= search_form_for @search, url: search_spaces_path do |f| %>
      <%= f.submit ("すべてのスペースをみる"), class: "btn btn-all" %>
      <% end %>
    </div>
  <!-- /min-width: 767px for desktop -->
</section>

<!-- Section 3 : Newest Review -->
<section class="container newest-review">
  <div class="title">
    <h2>新着の口コミ</h2>
    <div class="responsive-newest-review">
      <%= render @reviews.first(4) %>
    </div>
  </div>
</div>
</section>
<!-- /Section 3 : Newest Review -->

<!-- Section 4 : Area Search -->
<section class="container area-search">
<div class="title">
  <h2>エリアから探す</h2>
  <div class="area-search-title">
    <%= link_to area_path("shibuya") do %>
      <div class="col-md-4 col-sm-6 col-xs-6">
        <div id="shibuya" class="area-search-img" style="background-image: url('/images/shibuya.png')">
          <h3>渋谷</h3>
        </div>
      </div>
    <% end %>
    <%= link_to area_path("shinjuku") do %>
      <div class="col-md-4 col-sm-6 col-xs-6">
        <div id="shinjuku" class="area-search-img" style="background-image: url('/images/shinjuku.png')">
          <h3>新宿</h3>
        </div>
      </div>
    <% end %>
    <%= link_to area_path("harajuku") do %>
      <div class="col-md-4 col-sm-6 col-xs-6">
        <div id="harajuku" class="area-search-img" style="background-image: url('/images/harajuku.png')">
          <h3>原宿</h3>
        </div>
      </div>
    <% end %>
    <%= link_to area_path("akihabara") do %>
      <div class="col-md-4 col-sm-6 col-xs-6">
        <div id="akihabara" class="area-search-img" style="background-image: url('/images/akihabara.png')">
          <h3>秋葉原</h3>
        </div>
      </div>
    <% end %>
    <%= link_to area_path("tokyo") do %>
      <div class="col-md-4 col-sm-6 col-xs-6">
        <div id="tokyo" class="area-search-img" style="background-image: url('/images/tokyo.png')">
          <h3>東京</h3>
        </div>
      </div>
    <% end %>
    <%= link_to area_path("roppongi") do %>
      <div class="col-md-4 col-sm-6 col-xs-6">
        <div id="roppongi" class="area-search-img" style="background-image: url('/images/roppongi.png')">
          <h3>六本木</h3>
        </div>
      </div>
    <% end %>
  </div>
</div>
</section>
<!-- /Section 4 : Area Search -->

app/views/static_pages/policy.html.erb
<% provide(:title, "プライバシーポリシー") %>
<section class="policy container">
  <div class="title">
    <h2>プライバシーポリシー</h2>
  </div>
</section>

app/views/static_pages/terms.html.erb
<% provide(:title, "利用規約") %>
<section class="terms container">
  <div class="title">
    <h2>利用規約</h2>
  </div>
</section>