config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users, controllers: { registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions', confirmations: 'users/confirmations',
    passwords: 'users/passwords'
    }
  devise_scope :user do
    get '/users/sign_out', to: 'users/sessions#destroy'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'map/index'
  get 'areas/show'

  root 'static_pages#home'
  get'/about', to: 'static_pages#about'
  get'/contact', to: 'static_pages#contact'
  get'/advertise', to: 'static_pages#advertise'
  get'/terms', to: 'static_pages#terms'
  get'/policy', to: 'static_pages#policy'
  get '/', to: 'areas#show'

  resources :areas, param: :slag do
    resources :spaces, only: [:show] do
      member do
        get 'review'
        get 'photo'
        get 'map'
      end
    end
  end

  resources :spaces, only: [:show] do
    collection do
      get 'search'
    end
  end

  resources :reviews
  resources :users, only: [:show]
end

app/models/space.rb
class Space < ApplicationRecord
  has_many :reviews
  belongs_to :area
  belongs_to :space_image

  accepts_nested_attributes_for :space_image
  mount_uploader :image, ImageUploader
  geocoded_by :mapaddress
  after_validation :geocode
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only:[:show, :review, :photo, :map]
  add_breadcrumb 'スペースハッカー', :root_path
  add_breadcrumb 'エリア検索', :areas_show_path
  add_breadcrumb 'スペース', :area_space_path

  def new
      @space = Space.new(space_params)
      9.times { @space.space_images.build }
  end

  def review
    @reviews = Review.paginate(:page => params[:page], :per_page => 10)
  end

  def photo
  end

  def map
    @hash = Gmaps4rails.build_markers(@spaces) do |space, marker|
      marker.lat space.latitude
      marker.lng space.longitude
      marker.infowindow space.mapdescription
      marker.json({title: space.maptitle})
    end
  end

  def search
    @spaces = Space.paginate(page: params[:page], :per_page => 10)
    @areas = Area.all
  end
  private

  def space_params
    params.require(:space).permit(:name, :image, :genre, :minimum_fee, :access, :hour,
     :address, :phone, :website, :amenities, :plan, :guide,
      :description, :seats, :area_id, :space_image_id)
  end

  def set_space
    @space = Space.find(params[:id])
    @review = Review.new
  end

  def review_feed
    if logged_in?
      @review = current_user.reviews.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/map.html.erb
<% provide(:title, @space.name ) %>
<%= render 'layouts/spaceheader' %>
<section class="space-navigation navi-info container">
  <div class="title navi-info-box">
    <ul>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to "基本情報", area_space_path %></li>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to "口コミ", review_area_space_path %></li>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to "写真", photo_area_space_path %></li>
      <li class="col-md-3 col-sm-3 col-xs-3 selected"><a href="#">マップ</a></li>
    </ul>
  </div>
</section>
<!-- /Section 20 : My Page Navigation -->

<!-- Section 27 : Space Map -->
<section class="space-map container">
  <div class="title">
    <div class="space-map-contents">
      <div>
        <div id="map" style='width: 100%; height: 450px;'></div>
      </div>

      <script type="text/javascript">
          handler = Gmaps.build('Google');
          handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
            markers = handler.addMarkers(<%=raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
          });
      </script>

      <script type="text/javascript">
      function initMap() {

        var test ={lat: <%= @space.latitude %>, lng: <%= @space.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 15,
          center: test
        });
        var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);

        var contentString = '住所：<%= @space.address %>';
        var infowindow = new google.maps.InfoWindow({
          content: contentString
        });

        var marker = new google.maps.Marker({
          position:test,
          map: map,
          title: contentString
        });

        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });
      }
       </script>
       <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBzOpoIJy-9aLUOydR1E_PoMGg7itdjWpU&callback=initMap"async defer></script>

      <table class="table">
        <tbody>
          <tr>
            <td class="space-basic-table-title col-md-3 col-sm-3 col-xs-3">住所</td>
            <td class="space-basic-table-text col-md-9 col-sm-9 col-xs-9"><%= @space.address %></td>
          </tr>
          <tr>
            <td class="space-basic-table-title col-md-3 col-sm-3 col-xs-3">アクセス</td>
            <td class="space-basic-table-text col-md-9 col-sm-9 col-xs-9"><%= @space.access %></td>
          </tr>
          <tr>
            <td class="space-basic-table-title col-md-3 col-sm-3 col-xs-3">行き方</td>
            <td class="space-basic-table-text col-md-9 col-sm-9 col-xs-9"><%= @space.guide %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/spaces/photo.html.erb
<% provide(:title, @space.name ) %>
<%= render 'layouts/spaceheader' %>
<section class="space-navigation navi-info container">
  <div class="title navi-info-box">
    <ul>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to "基本情報", area_space_path %></li>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to "口コミ", review_area_space_path %></li>
      <li class="col-md-3 col-sm-3 col-xs-3 selected"><a href="#">写真</a></li>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to "マップ", map_area_space_path %></li>
    </ul>
  </div>
</section>

<section class="space-albums container">
  <div class="title">
    <div class="space-albums-images col-md-4 col-sm-4 col-xs-4">
      <%= image_tag @space.space_image.image_1 %>
    </div>
    <div class="space-albums-images col-md-4 col-sm-4 col-xs-4">
      <%= image_tag @space.space_image.image_2 %>
    </div>
    <div class="space-albums-images col-md-4 col-sm-4 col-xs-4">
      <%= image_tag @space.space_image.image_3 %>
    </div>

    <div class="space-albums-images col-md-4 col-sm-4 col-xs-4">
      <%= image_tag @space.space_image.image_4 %>
    </div>
    <div class="space-albums-images col-md-4 col-sm-4 col-xs-4">
      <%= image_tag @space.space_image.image_5 %>
    </div>
    <div class="space-albums-images col-md-4 col-sm-4 col-xs-4">
      <%= image_tag @space.space_image.image_6 %>
    </div>

    <div class="space-albums-images col-md-4 col-sm-4 col-xs-4">
      <%= image_tag @space.space_image.image_7 %>
    </div>
    <div class="space-albums-images col-md-4 col-sm-4 col-xs-4">
      <%= image_tag @space.space_image.image_8 %>
    </div>
    <div class="space-albums-images col-md-4 col-sm-4 col-xs-4">
      <%= image_tag @space.space_image.image_9 %>
    </div>
  </div>
</section>

app/views/spaces/review.html.erb
<% provide(:title, @space.name ) %>
<%= render 'layouts/spaceheader' %>
<section class="space-navigation navi-info container">
  <div class="title navi-info-box">
    <ul>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to "基本情報", area_space_path %></li>
      <li class="col-md-3 col-sm-3 col-xs-3 selected"><a href="#">口コミ</a></li>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to "写真", photo_area_space_path %></li>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to "マップ", map_area_space_path %></li>
    </ul>
  </div>
</section>

<section class="space-basic-review container">
  <div class="title">
    <div class="responsive-newest-review">
      <% @space.reviews.each do |review| %>
      <div class="review" id="review">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="col-md-4 col-sm-6 col-xs-8 review-head">
            <div class="col-md-2 col-sm-4 col-xs-3 review-head-icon">
              <% if review.user.image? %>
              <%= image_tag review.user.image %>
              <% else %>
              <img src="/images/icon.jpeg" />
              <% end %>
            </div>
            <div class="col-md-10 col-sm-8 col-xs-9 review-head-summary">
              <p><%= link_to review.user.name, review.user, class: "review-name" %></p>
              <p><%= link_to review.space.name, area_space_path(area_slag: review.space.area.slag, id: review.space.id), class: "review-space" %></p>
            </div>
          </div>
          <div class="col-md-8 col-sm-6 col-xs-4 review-timestamp">
            <%= time_ago_in_words(review.created_at) %>前
          </div>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12 review-rate">
          <span class="rate rate-<%= review.rate %>"></span><span class="review-rate-title"><%= review.title %></span>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12 review-contents desktop">
          <%= truncate(review.content, :length => 120)%><%= link_to "続きを読む", review %>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12 review-contents mobile">
          <%= truncate(review.content, :length => 30)%><%= link_to "続きを読む", review %>
        </div>

      </div>
      <p class="upper-line"></p>
      <% end %>
    </div>
    <%= will_paginate @reviews %>
  </div>
</section>

app/views/spaces/search.html.erb
<% provide(:title, "すべてのスペース一覧" ) %>
<%= render 'shared/search_form' %>

<section class="search-result container">
  <div class="title">
    <h2>すべての検索結果</h2>

    <% @search_spaces.each do |space| %>
    <div class="search-result-card">
      <div class="search-result-card-img col-md-2 col-sm-3 col-xs-2">
        <a href="#"><%= image_tag space.image %></a>
      </div>
      <div class="search-result-card-title col-md-7 col-sm-6 col-xs-7">
        <a href="./space.html"><h3><%= link_to space.name, area_space_path(area_slag: space.area.slag, id: space.id) %></h3></a>
        <p><span class="rate rate30"></span><span class="search-result-review-numbers"></p>
        <p><span class="search-result-category"><%= space.name %></span>・<span><%= space.minimum_fee %></span></p>
      </div>
      <div class="search-result-card-address col-md-3 col-sm-3 col-xs-7">
        <p class="search-result-card-address-area">
          <img src="/images/map-marker.png" />
          <span><%= space.area.try(:name) %></span>
        </p>
        <p class="search-result-card-address-detail hidden-xs">
          <%= space.address %>
        </p>
      </div>
      <div class="search-result-card-contents col-md-10 hidden-sm hidden-xs">
        <p><%= truncate(space.description, :length => 110)%><%= link_to "続きを読む", space %></p>
      </div>
    </div>
    <% end %>

    <%= will_paginate @spaces %>
  </div>
</section>

app/views/spaces/show.html.erb
<% provide(:title, @space.name ) %>
<%= render 'layouts/spaceheader' %>

<!-- Section 20 : Space Navigation -->
<section class="space-navigation navi-info container">
  <div class="title navi-info-box">
    <ul>
      <li class="col-md-3 col-sm-3 col-xs-3 selected"><a href="#">基本情報</a></li>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to "口コミ", review_area_space_path %></li>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to "写真", photo_area_space_path %></li>
      <li class="col-md-3 col-sm-3 col-xs-3"><%= link_to "マップ", map_area_space_path %></li>
    </ul>
  </div>
</section>
<!-- /Section 20 : My Page Navigation -->

<!-- Section 21 : Space Basic Image -->
<section class="space-basic-image container desktop">
  <div class="title">
    <div class="space-basic-image-albums col-md-4 col-sm-4">
      <%= image_tag @space.space_image.image_1 %>
    </div>
    <div class="space-basic-image-albums col-md-4 col-sm-4">
      <%= image_tag @space.space_image.image_2 %>
    </div>
    <div class="space-basic-image-albums col-md-4 col-sm-4">
      <%= image_tag @space.space_image.image_3 %>
    </div>
    <div class="space-basic-image-more col-md-12">
      <%= link_to "公式写真をもっと見る", photo_area_space_path %>
    </div>
  </div>
</section>
<!-- /Section 21 : Space Basic Image -->

<!-- Section 22 : Space Basic Text -->
<section class="space-basic-text container">
  <div class="title">
    <h2>スペースの詳細</h2>
    <p>
      <%= @space.description %>
    </p>
  </div>
</section>
<!-- Section 22 : Space Basic Text -->

<!-- Section 23 : Space Basic Table -->
<section class="space-basic-table container">
  <div class="title">
    <h2>基本情報</h2>
    <table class="table">
      <tbody>
        <tr>
          <td class="space-basic-table-title col-md-3 col-sm-3 col-xs-3">スペース名</td>
          <td class="space-basic-table-text col-md-9 col-sm-9 col-xs-9"><%= @space.name %></td>
        </tr>
        <tr>
          <td class="space-basic-table-title col-md-3 col-sm-3 col-xs-3">ジャンル</td>
          <td class="space-basic-table-text col-md-9 col-sm-9 col-xs-9"><%= @space.genre %></td>
        </tr>
        <tr>
          <td class="space-basic-table-title col-md-3 col-sm-3 col-xs-3">アクセス</td>
          <td class="space-basic-table-text col-md-9 col-sm-9 col-xs-9"><%= @space.access %></td>
        </tr>
        <tr>
          <td class="space-basic-table-title col-md-3 col-sm-3 col-xs-3">電話番号</td>
          <td class="space-basic-table-text col-md-9 col-sm-9 col-xs-9"><%= @space.phone %></td>
        </tr>
        <tr>
          <td class="space-basic-table-title col-md-3 col-sm-3 col-xs-3">公式サイト</td>
          <td class="space-basic-table-text col-md-9 col-sm-9 col-xs-9"><%= @space.website %></td>
        </tr>
        <tr>
          <td class="space-basic-table-title col-md-3 col-sm-3 col-xs-3">席数</td>
          <td class="space-basic-table-text col-md-9 col-sm-9 col-xs-9"><%= @space.seats %>席</td>
        </tr>
        <tr>
          <td class="space-basic-table-title col-md-3 col-sm-3 col-xs-3">住所</td>
          <td class="space-basic-table-text col-md-9 col-sm-9 col-xs-9"><%= @space.address %><br /><span>※ お問い合わせの際は「"スペースハッカー"を見たとお伝えください。</span></td>
        </tr>
        <tr>
          <td class="space-basic-table-title col-md-3 col-sm-3 col-xs-3">料金プラン</td>
          <td class="space-basic-table-text col-md-9 col-sm-9 col-xs-9">ドロップイン：2時間500円、1日1000円<br />月額会員：9,000円</td>
        </tr>
        <tr>
          <td class="space-basic-table-title col-md-3 col-sm-3 col-xs-3">設備</td>
          <td class="space-basic-table-text col-md-9 col-sm-9 col-xs-9"><%= @space.amenities %></td>
        </tr>
      </tbody>
    </table>
  </div>
</section>
<!-- /Section 23 : Space Basic Table -->

<!-- Section 24 : Space Basic Review -->
<section class="space-basic-review container">
  <div class="title">
    <h2>口コミ</h2>
  <% @space.reviews.first(4).each do |review| %>
  <div class="review" id="review">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="col-md-4 col-sm-6 col-xs-8 review-head">
        <div class="col-md-2 col-sm-4 col-xs-3 review-head-icon">
          <% if review.user.image? %>
          <%= image_tag review.user.image %>
          <% else %>
          <img src="/images/icon.jpeg" />
          <% end %>
        </div>
        <div class="col-md-10 col-sm-8 col-xs-9 review-head-summary">
          <p><%= link_to review.user.name, review.user, class: "review-name" %></p>
          <p><%= link_to review.space.name, area_space_path(area_slag: review.space.area.slag, id: review.space.id), class: "review-space" %></p>
        </div>
      </div>
      <div class="col-md-8 col-sm-6 col-xs-4 review-timestamp">
        <%= time_ago_in_words(review.created_at) %>前
      </div>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 review-rate">
      <span class="rate rate-<%= review.rate %>"></span><span class="review-rate-title"><%= review.title %></span>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 review-contents desktop">
      <%= truncate(review.content, :length => 120)%><%= link_to "続きを読む", review %>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 review-contents mobile">
      <%= truncate(review.content, :length => 30)%><%= link_to "続きを読む", review %>
    </div>
  </div>
  <p class="upper-line"></p>
  <% end %>
  <div class="space-basic-image-more col-md-12">
    <%= link_to "口コミをもっと見る", review_area_space_path %>
  </div>
</section>