config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users, controllers: { registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions', confirmations: 'users/confirmations',
    passwords: 'users/passwords'
    }
  devise_scope :user do
    get '/users/sign_out', to: 'users/sessions#destroy'
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'map/index'
  get 'areas/show'

  root 'static_pages#home'
  get'/about', to: 'static_pages#about'
  get'/contact', to: 'static_pages#contact'
  get'/advertise', to: 'static_pages#advertise'
  get'/terms', to: 'static_pages#terms'
  get'/policy', to: 'static_pages#policy'
  get '/', to: 'areas#show'

  resources :areas, param: :slag do
    resources :spaces, only: [:show] do
      member do
        get 'review'
        get 'photo'
        get 'map'
      end
    end
  end

  resources :spaces, only: [:show] do
    collection do
      get 'search'
    end
  end

  resources :reviews
  resources :users, only: [:show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :spaces
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :space
  default_scope -> { order(created_at: :desc)}
  validates :user_id, presence: true
  # validates :space_id, presence: true
  validates :content, presence: true, length: { maximum: 2000, minimum: 100 }
end

app/models/space.rb
class Space < ApplicationRecord
  has_many :reviews
  belongs_to :area
  belongs_to :space_image

  accepts_nested_attributes_for :space_image
  mount_uploader :image, ImageUploader
  geocoded_by :mapaddress
  after_validation :geocode
end

app/models/space_image.rb
class SpaceImage < ApplicationRecord
  has_many :spaces
  mount_uploader :image_1, SpaceImageUploader
  mount_uploader :image_2, SpaceImageUploader
  mount_uploader :image_3, SpaceImageUploader
  mount_uploader :image_4, SpaceImageUploader
  mount_uploader :image_5, SpaceImageUploader
  mount_uploader :image_6, SpaceImageUploader
  mount_uploader :image_7, SpaceImageUploader
  mount_uploader :image_8, SpaceImageUploader
  mount_uploader :image_9, SpaceImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  mount_uploader :image, ImageUploader
  validates :name, presence: true
  has_many :reviews

  def self.find_for_oauth(auth)
    where(uid: auth.uid, provider: auth.provider).first_or_create do |user|
      user.uid = auth.uid
      user.provider = auth.provider
      user.name = auth.info.name
      user.email = auth.info.email
      user.token = auth.credentials.token
      user.password = Devise.friendly_token[4, 30]
    end
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["name = :value OR lower(email) = lower(:value)", { :value => login }]).first
    else
      where(conditions).first
    end
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    clean_up_passwords
    update_attributes(params, *options)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :background, :uid, :provider, :token)
  end

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_search
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def set_search
    @search = Space.ransack(params[:q])
    @search_spaces = @search.result.paginate(page: params[:page])
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :background, :image])
  end

  private

  def signed_in_user
    unless signed_in?
      store_location
      flash[:danger] = "ログインしてください"
      redirect_to login_url
    end
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def show
    @area = Area.find_by(slag: params[:slag])
    @spaces = Space.paginate(:page => params[:page], :per_page => 10)
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    @hash = Gmaps4rails.build_markers(@spaces) do |space, marker|
      marker.lat space.latitude
      marker.lng space.longitude
      marker.infowindow space.mapdescription
      marker.json({title: space.maptitle})
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :signed_in_user
  before_action :correct_user, only: :destroy

  def create
   @review = current_user.reviews.build(review_params)
   if @review.save
     flash[:success] = "コメントが投稿されました！"
     redirect_to root_path
   else
     #flash.now[:alert] = 'コメントの投稿に失敗しました。'
     render 'new'
   end
 end

  def show
    @review = Review.find(params[:id])
  end

  def new
    @review = current_user.reviews.build if signed_in?
  end

  def destroy
    @review.destroy
    flash[:success] = "口コミが削除されました"
    redirect_to request.referrer || root_url
  end

  def edit
  end

  def update
  end

  private

  def review_params
    params.require(:review).permit(:id,:content, :rate, :title, :space_id, :user_id)
  end

  def correct_user
    @review = current_user.reviews.find_by(id: params[:id])
    redirect_to root_url if @review.nil?
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  before_action :set_space, only:[:show, :review, :photo, :map]
  add_breadcrumb 'スペースハッカー', :root_path
  add_breadcrumb 'エリア検索', :areas_show_path
  add_breadcrumb 'スペース', :area_space_path

  def new
      @space = Space.new(space_params)
      9.times { @space.space_images.build }
  end

  def review
    @reviews = Review.paginate(:page => params[:page], :per_page => 10)
  end

  def photo
  end

  def map
    @hash = Gmaps4rails.build_markers(@spaces) do |space, marker|
      marker.lat space.latitude
      marker.lng space.longitude
      marker.infowindow space.mapdescription
      marker.json({title: space.maptitle})
    end
  end

  def search
    @spaces = Space.paginate(page: params[:page], :per_page => 10)
    @areas = Area.all
  end
  private

  def space_params
    params.require(:space).permit(:name, :image, :genre, :minimum_fee, :access, :hour,
     :address, :phone, :website, :amenities, :plan, :guide,
      :description, :seats, :area_id, :space_image_id)
  end

  def set_space
    @space = Space.find(params[:id])
    @review = Review.new
  end

  def review_feed
    if logged_in?
      @review = current_user.reviews.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.paginate(page: params[:page], :per_page => 10)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confiramation, :image, :background)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。
  def full_title(page_title = '')
    base_title = "スペースハッカー"
    if page_title.empty?
      base_title
    else
      base_title + " - " + page_title
    end
  end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="desktop">
    <div class="container">
      <div class="footer-top title">
        <div class="col-md-5 col-sm-5 footer-title-logo">
          <img src="/images/footer_logo.png" />
        </div>
        <div class="col-md-4 col-sm-4 footer-title-contents">
          <p>Space Hackerについて</p>
          <ul class="col-md-6 col-sm-6">
            <li><%= link_to "ホーム", root_path %></li>
            <li><%= link_to "運営会社", 'http://gociao.com', :target=>["_blank"] %></li>
            <li><%= link_to "広告掲載", advertise_path %></li>
            <li><%= link_to "お問い合わせ", contact_path %></li>
          </ul>
          <ul class="col-md-6 col-sm-6">
            <li><%= link_to "サイトについて", about_path %></li>
            <li><%= link_to "利用規約", terms_path %></li>
            <li><%= link_to "ポリシー", policy_path %></li>
            <li><%= link_to "ブログ", 'http://spacehacker.jp/blog', :target=>["_blank"] %></li>
          </ul>
        </div>
        <div class="col-md-3 col-sm-3 footer-title-contents">
          <p>SNS</p>
          <ul class="col-md-12 col-sm-12">
            <li><a href="#" target="_blank">Instagram</a></li>
            <li><a href="#" target="_blank">Twitter</a></li>
            <li><a href="#" target="_blank">LINE@</a></li>
            <li><a href="#" target="_blank">Facebook</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-bottom">
      <span>Space Hacker[スペースハッカー]｜仕事で使えるスペース総合サイト</span>
      <span style="float: right;">Copyright Ciao Technologies Inc, 2017 All Rights Reserved.</span>
    </div>
  </div>

  <div class="mobile">
    <ul>
      <li><a href="#" target="_blank"><img src="/images/facebook.png" /></a></li>
      <li><a href="#" target="_blank"><img src="/images/twitter.png" /></a></li>
      <li><a href="#" target="_blank"><img src="/images/instagram.png" /></a></li>
    </ul>

    <ul>
      <li><a href="http://gociao.com" target="_blank">運営会社</a></li>
      <li><a href="./contact.html">広告掲載</a></li>
      <li><a href="#">ブログ</a></li>
    </ul>

    <ul>
      <li><a href="#">よくある質問</a></li>
      <li><a href="#">お問い合わせ</a></li>
      <li><a href="#">利用規約</a></li>
    </ul>

    <span>Copyright © Ciao Technologies, Inc. All Rights Reserved.</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-white">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="./index.html"><%= link_to image_tag("text_logo.png", alt: "SpaceHacker logo", id: "logo"),
        root_path %></a>
      </div>
      <% if user_signed_in? %>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right nav-hover">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "最近の口コミ", current_user %></li>
              <li><%= link_to "アカウント", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
      <% else %>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right nav-hover">
          <li><%= link_to "新規会員登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></a></li>
        </ul>
      </div><!--/.nav-collapse -->
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_spaceheader.html.erb
<section class="space-head">
  <div id="carousel-example-generic" class="carousel slide mobile" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-generic" data-slide-to="1"></li>
      <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      <li data-target="#carousel-example-generic" data-slide-to="3"></li>
      <li data-target="#carousel-example-generic" data-slide-to="4"></li>
      <li data-target="#carousel-example-generic" data-slide-to="5"></li>
      <li data-target="#carousel-example-generic" data-slide-to="6"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active space-image">
        <%= image_tag @space.image %>
      </div>
      <div class="item space-image">
        <%= image_tag @space.space_image.image_1 %>
      </div>
      <div class="item space-image">
        <%= image_tag @space.space_image.image_2 %>
      </div>
      <div class="item space-image">
        <%= image_tag @space.space_image.image_3 %>
      </div>
      <div class="item space-image">
        <%= image_tag @space.space_image.image_4 %>
      </div>
      <div class="item space-image">
        <%= image_tag @space.space_image.image_5 %>
      </div>
      <div class="item space-image">
        <%= image_tag @space.space_image.image_6 %>
      </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="container">
    <div class="title">
      <div class="space-head-img desktop col-md-2 col-sm-3">
        <%= image_tag @space.image %>
      </div>
      <div class="space-head-info col-md-7 col-sm-5">
      <h3><%= @space.name %></h3>
        <ul>
          <li><strong>ジャンル:</strong><span><%= @space.genre %></span></li>
          <li><strong>予算:</strong><span><%= @space.minimum_fee %></span></li>
        </ul>
        <ul>
          <li><strong>最寄り駅:</strong><span><%= @space.access %></span>
          <li><strong>営業時間:</strong><span><%= @space.hour %></span></li>
        </ul>
        <ul>
          <li><strong>住所:</strong><span><%= @space.address %></span></li>
        </ul>
      </div>
      <div class="space-head-action col-md-3 col-sm-4">
        <ul>
          <li><button class="btn btn-form" data-toggle="modal" data-target="#myModal">口コミを登録する</button></li>
        </ul>
      </div>
    </div>
  </div>
</section>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="z-index: 30000;">
  <div class="modal-dialog" role="document">
    <%= form_for(@review) do |f| %>
    <div class="modal-content">
      <%= render 'shared/error_messages', object: f.object %>
      <div class="modal-body">
        <div class="title page-form account-form">
          <h2>口コミを登録する</h2>
          <form>
            <div class="form-group review-form-space">
              <h3><%= @space.name %></h3>
              <%= f.hidden_field :space_id, value: @space.id %>
            </div>
            <div class="form-group">
              <label for="exampleInputName">口コミを入力する</label><br />
              <%= f.select :rate, {'1' => 1, '2' => 2, '3' => 3, '4' => 4, '5' => 5,}, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.text_field :title, class: "form-control", placeholder: "タイトル" %>
            </div>
            <div class="form-group">
              <%= f.text_area :content, class: "form-control", placeholder: "口コミ内容", rows: "5" %>
            </div>
          </form>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
        <%= f.submit "投稿する", class: "btn btn-form btn-modal" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_userheader.html.erb
<section class="mypage-head container title">
  <div class="mypage-head-icon col-md-2 col-sm-4 col-xs-4">
    <% if @user.image? %>
    <%= image_tag @user.image %>
    <% else %>
    <img src="/images/icon.jpeg" />
    <% end %>
  </div>
  <div class="mypage-head-contents col-md-10 col-sm-8 col-xs-8">
    <h2><%= @user.name %></h2>
    <p><%= @user.background %></p>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    <script src="http://cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src="http://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-1.8.3.min.js"></script>
    <%= analytics_init if Rails.env.production? %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_breadcrumbs.html.erb
<% if elements.present? %>
  <nav class="breadcrumbs desktop">
    <div class="container">
      <ul class="breadcrumbs-contents title">
        <% elements[0..-2].each do |element| %>
        <li>
        <% if element.path.present? %>
          <a href="<%= element.path %>"><%= element.name %></a>
        <% else %>
          <%= element.name %>
        <% end %>
          <span class="divider">/</span>
        </li>
        <% end %>

        <%= elements.last.name %>
      </ul>
    </div>
  </nav>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_review_form.html.erb
<%= form_for(@review) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "口コミを入力する" %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_search_form.html.erb
<section class="search-result-bar container">
  <%= search_form_for @search, url: search_spaces_path do |f| %>
  <div class="title">
    <%= f.text_field :description_cont, placeholder: "キーワードを検索する", class: "form-control search-result-keyword col-md-6" %>
    <%= f.submit ("検索する"), class: "btn btn-form desktop col-md-6" %>
  </div>
  <% end %>
</section>